--[[ Configuration settings ]]
Config = {}

--[[ Locale setting for language localization. ]]
Config.Locale             = "en"

---@type EventName | nil -- Cloth menu event name for house wardrobe
Config.ClothMenuEventName = nil

--[[ If qb-inventory is used and the version is higher than 2.0.0 then enable this setting, otherwise set value to 'false' ]]
Config.NewInventoryQB = true

--[[ MetaKeys | Only ESX | if your esx version is old or you get a "setMeta" error. Set value to false. ]]
Config.MetaKeys = true

--[[ Commands ]]
Config.Commands = {
    -- Main command,the menu wheree verything is managed.
    useMainPanel = "pixelhouse",
    -- Create new house | Only admin.
    useCreateHouse = "createpixelhouse",
    -- Let the player who rings the bell into the house
    useAnswerDoorBell = "checkdoor",
}

--[[ Open Panel With Tablet Item ]]
Config.OpenPanelWithTablet = {
    active = false,
    itemName = "tablet",
}

--[[ Add blips to houses for sale. ]]
Config.SaleHouseBlip = {
    active = true,
    sprite = 350,
    color = 2,
    scale = 0.7,
}

--[[ Add blips to purchased houses. If the other home blip is open, it updates with it. ]]
Config.HouseOwnedBlip = {
    active = true,
    sprite = 40,
    color = 3,
    scale = 0.7,
}

--[[ Players can only buy 1 house, If false there is no limit ! ]]
Config.MaxHouseLimitPerPlayer = 1

--[[ Stairs can be placed or removed. ]]
Config.EditableStairs = true

--[[ Place/Rooms can be placed or removed. ]]
Config.EditableRooms = true

--[[ Furniture-based stash ]]
Config.StashOptions = {
    active = true,
    slots = 10,
    maxWeight = 1000000,
}

--[[ Real-Estate ]]
--[[ Use Commands.useCreateHouse Command. Players can create a house. They cannot do anything else. It is not a detailed system. ]]
Config.RealEstate = {
    enable = true,
    jobs = {
        ["admin"] = true,
    },
}

--[[ Furniture-based wardrobe ]]
Config.WardrobeOptions = {
    active = true,
}

--[[ Raid ]]
Config.Raid = {
    enable = false,         -- Enable/Disable raiding
    canUseStash = true,     -- Can access stashes.
    itemRequired = {        -- Item required to raid
        removeItem = true,  -- Remove item from inventory
        name = "lockpick",  -- Item name
        label = "LockPick", -- Item label
        itemCount = 1,      -- Item count
    },
}

Config.InteriorHouseTypes = {
    ["square"] = {
        label = "شقة بـدورين تحت الارض",
        door_coords = vec3(363.1291, -1268.3627, -84.2126),
        enter_coords = vec4(363.1167, -1269.9006, -84.2126, 162.3873),
        max_stash_count = 10,
    },
    ["rectangle"] = {
        label = "شقة بـدورين تحت الارض",
        door_coords = vec3(402.9340, -1263.9220, -84.0736),
        enter_coords = vec4(402.8653, -1265.3367, -84.0736, 176.2434),
        max_stash_count = 10,
    },
    ["furnished"] = {
        label = "شقة صغيرة مؤثثة",
        door_coords = vec3(93.6972, -485.8475, -109.0118),
        enter_coords = vec4(92.1094, -485.8838, -109.0118, 91.5934),
        max_stash_count = 10,
    },
    ["apa_v_mp_h"] = {
        label = "شقة كبيرة مؤثثة",
        door_coords = vec3(-782.2, 319, 187.9),
        enter_coords = vec3(-782.2, 319, 187.9),
        max_stash_count = 10,
    },
}

--[[ InteriorHouseGarage]]
Config.InteriorHouseGarage = {
    coords = {
        enter = vec3(520.00000000, -2625.00000000, -39.69168000),
        exit = vec3(519.9845, -2637.2595, -38.6916),
        vehicles = {
            vec4(514.0, -2612.69, -38.5, 273.83),
            vec4(514.0, -2616.69, -38.5, 273.83),
            vec4(514.0, -2620.69, -38.5, 273.83),
            vec4(514.0, -2624.69, -38.5, 273.83),
            vec4(514.0, -2628.69, -38.5, 273.83),
            vec4(514.0, -2632.69, -38.5, 273.83),
            vec4(525.46, -2612.53, -38.5, 92.52),
            vec4(525.46, -2616.64, -38.5, 92.52),
            vec4(525.46, -2620.64, -38.5, 92.52),
            vec4(525.46, -2624.64, -38.5, 92.52),
            vec4(525.46, -2628.64, -38.5, 92.52),
            vec4(525.46, -2632.64, -38.5, 92.52),
        }
    }
}

--[[ Houses ]]
--[[ It will be added to the database automatically. You can add it from here or from the game. ]]
Config.Houses = {
    [1] = {
        houseId = 1,
        label = "Eclipse towers 1",
        price = 250000,
        door_coords = vector4(-777.29, 312.91, 85.7, 175.0),
        garage_coords = vector4(-800.55, 332.31, 85.28, 180.0),
        coords_label = "Eclipse Towers 1",
    },
    [2] = {
        houseId = 2,
        label = "Eclipse towers 2",
        price = 250000,
        door_coords = vector4(-775.07, 312.91, 85.7, 175.0),
        garage_coords = vector4(-800.55, 332.31, 85.28, 180.0),
        coords_label = "Eclipse Towers 2",
    },
    [3] = {
        houseId = 3,
        label = "Eclipse towers 3",
        price = 250000,
        door_coords = vector4(-772.75, 312.91, 85.7, 175.0),
        garage_coords = vector4(-800.55, 332.31, 85.28, 180.0),
        coords_label = "Eclipse Towers 3",
    },
    [4] = {
        houseId = 4,
        label = "Eclipse towers 4",
        price = 250000,
        door_coords = vector4(-770.47, 312.91, 85.7, 175.0),
        garage_coords = vector4(-800.55, 332.31, 85.28, 180.0),
        coords_label = "Eclipse Towers 4",
    },
    [5] = {
        houseId = 5,
        label = "Rockford Hills 2835",
        price = 300000,
        door_coords = vector4(-824.69122314453, 422.11721801758, 92.124183654785, 4.6266412734985),
        garage_coords = vector4(-805.76806640625, 424.80856323242, 91.164764404297, 358.12051391602),
        coords_label = "Rockford Hills 2835",
    },
    [6] = {
        houseId = 6,
        label = "Rockford Hills",
        price = 200000,
        door_coords = vector4(-762.09802246094, 430.98797607422, 100.19689178467, 20.41704750061),
        garage_coords = vector4(-756.37158203125, 439.49935913086, 99.332260131836, 32.027355194092),
        coords_label = "Rockford Hills",
    },
    [7] = {
        houseId = 7,
        label = "Vinewood Hills",
        price = 350000,
        door_coords = vector4(-784.31121826172, 459.03790283203, 100.17911529541, 214.1674041748),
        garage_coords = vector4(-766.138671875, 465.86376953125, 100.04393768311, 221.47233581543),
        coords_label = "Vinewood Hills",
    },
    [8] = {
        houseId = 8,
        label = "Vinewood Hills",
        price = 500000,
        door_coords = vector4(-717.91760253906, 449.08349609375, 106.90912628174, 33.661552429199),
        garage_coords = vector4(-737.60144042969, 443.07455444336, 106.45419311523, 22.544794082642),
        coords_label = "Vinewood Hills",
    },
    [9] = {
        houseId = 9,
        label = "Vinewood Hills",
        price = 400000,
        door_coords = vector4(-721.67749023438, 490.09130859375, 109.3854598999, 207.96739196777),
        garage_coords = vector4(-714.39373779297, 498.74905395508, 108.78099822998, 205.49346923828),
        coords_label = "Vinewood Hills",
    },
    [10] = {
        houseId = 10,
        label = "Vinewood Hills",
        price = 450000,
        door_coords = vector4(-678.90905761719, 511.69137573242, 113.52600860596, 195.72416687012),
        garage_coords = vector4(-688.29125976563, 503.49453735352, 109.88667297363, 22.495265960693),
        coords_label = "Vinewood Hills",
    },
    [11] = {
        houseId = 11,
        label = "Vinewood Hills",
        price = 300000,
        door_coords = vector4(-667.16119384766, 471.87008666992, 114.13648986816, 12.573315620422),
        garage_coords = vector4(0.0, 0.0, 0.0, 0.0),  -- No garage coords provided
        coords_label = "Vinewood Hills",
    },
    [12] = {
        houseId = 12,
        label = "Vinewood Hills",
        price = 400000,
        door_coords = vector4(-640.84423828125, 519.70147705078, 109.68778991699, 191.83695983887),
        garage_coords = vector4(-632.14758300781, 518.72601318359, 109.23080444336, 190.06854248047),
        coords_label = "Vinewood Hills",
    },
    [13] = {
        houseId = 13,
        label = "Vinewood Hills",
        price = 200000,
        door_coords = vector4(-622.80877685547, 489.19741821289, 108.85733795166, 10.021870613098),
        garage_coords = vector4(-615.18334960938, 493.49322509766, 107.72460174561, 9.0182447433472),
        coords_label = "Vinewood Hills",
    },
    [14] = {
        houseId = 14,
        label = "Vinewood Hills",
        price = 450000,
        door_coords = vector4(-595.43835449219, 530.15588378906, 107.7551574707, 189.64042663574),
        garage_coords = vector4(-586.51824951172, 529.07232666016, 107.43088531494, 227.30792236328),
        coords_label = "Vinewood Hills",
    },
    [15] = {
        houseId = 15,
        label = "Vinewood Hills",
        price = 350000,
        door_coords = vector4(-580.45324707031, 491.8498840332, 108.90293884277, 15.849659919739),
        garage_coords = vector4(-575.24328613281, 496.98516845703, 106.05406188965, 9.680495262146),
        coords_label = "Vinewood Hills",
    },
    [16] = {
        houseId = 16,
        label = "Vinewood Hills",
        price = 175000,
        door_coords = vector4(-526.97869873047, 517.45843505859, 112.9415512085, 43.375503540039),
        garage_coords = vector4(-527.32049560547, 526.83068847656, 111.6321182251, 45.063865661621),
        coords_label = "Vinewood Hills",
    },
    [17] = {
        houseId = 17,
        label = "Vinewood Hills",
        price = 125000,
        door_coords = vector4(-554.58203125, 540.92437744141, 110.70709228516, 152.44755554199),
        garage_coords = vector4(-543.84783935547, 544.21716308594, 109.98294067383, 279.5569152832),
        coords_label = "Vinewood Hills",
    },
    [18] = {
        houseId = 18,
        label = "Vinewood Hills",
        price = 450000,
        door_coords = vector4(-537.00787353516, 477.494140625, 103.1936416626, 59.317764282227),
        garage_coords = vector4(-537.27593994141, 484.15759277344, 102.57349395752, 49.000453948975),
        coords_label = "Vinewood Hills",
    },
    [19] = {
        houseId = 19,
        label = "Vinewood Hills",
        price = 275000,
        door_coords = vector4(-532.45989990234, 485.25451660156, 106.70455932617, 197.50054931641),
        garage_coords = vector4(-533.58270263672, 492.14074707031, 106.36367034912, 236.61376953125),
        coords_label = "Vinewood Hills",
    },
    [20] = {
        houseId = 20,
        label = "House",
        price = 100000,
        door_coords = vector4(945.9721, -518.7975, 60.0, 271.2817),
        garage_coords = vector4(949.2786, -514.9356, 59.0, 12.0338),
        coords_label = "West Mirror Drive",
    },
    [21] = {
        houseId = 21,
        label = "House ON RoxWood County #001",
        price = 800000,
        door_coords = vector4(-419.7520, 7495.6333, 7.8648, 1.7778),
        garage_coords = vector4(-424.1891, 7492.0293, 6.5997, 358.9748),
        coords_label = "RoxWood County #001",
    },
    [22] = {
        houseId = 22,
        label = "House ON RoxWood County #002",
        price = 650000,
        door_coords = vector4(-446.6895, 7497.9077, 6.9284, 358.6154),
        garage_coords = vector4(-438.2722, 7489.2627, 6.8758, 190.8796),
        coords_label = "RoxWood County #002",
    },
    [23] = {
        houseId = 23,
        label = "House ON RoxWood County #003",
        price = 920000,
        door_coords = vector4(-469.1960, 7499.9346, 7.4682, 5.2979),
        garage_coords = vector4(-474.3723, 7487.8062, 8.1395, 178.9649),
        coords_label = "RoxWood County #003",
    },
    [24] = {
        houseId = 24,
        label = "House ON RoxWood County #004",
        price = 750000,
        door_coords = vector4(-492.5987, 7495.8423, 8.0195, 177.4391),
        garage_coords = vector4(-499.5905, 7486.5244, 8.4783, 358.0826),
        coords_label = "RoxWood County #004",
    },
    [25] = {
        houseId = 25,
        label = "House ON RoxWood County #005",
        price = 550000,
        door_coords = vector4(-516.1432, 7500.5884, 8.5312, 346.8574),
        garage_coords = vector4(-521.6926, 7487.1729, 8.6012, 358.4159),
        coords_label = "RoxWood County #005",
    },
    [26] = {
        houseId = 26,
        label = "House ON RoxWood County #006",
        price = 370000,
        door_coords = vector4(-579.3942, 7452.3418, 7.3822, 178.9471),
        garage_coords = vector4(-587.6548, 7459.1382, 7.3980, 339.3994),
        coords_label = "RoxWood County #006",
    },
    [27] = {
        houseId = 27,
        label = "House ON RoxWood County #007",
        price = 480000,
        door_coords = vector4(-611.7000, 7454.1392, 7.1537, 175.0223),
        garage_coords = vector4(-603.9593, 7463.3911, 7.0880, 182.9091),
        coords_label = "RoxWood County #007",
    },
    [28] = {
        houseId = 28,
        label = "House ON RoxWood County #008",
        price = 820000,
        door_coords = vector4(-625.2980, 7503.0259, 6.5434, 343.1587),
        garage_coords = vector4(-633.7324, 7495.1353, 6.7824, 194.2907),
        coords_label = "RoxWood County #008",
    },
    [29] = {
        houseId = 29,
        label = "House ON RoxWood County #009",
        price = 900000,
        door_coords = vector4(-656.6877, 7495.1016, 8.1716, 70.0489),
        garage_coords = vector4(-651.7780, 7486.3945, 6.9731, 50.8018),
        coords_label = "RoxWood County #009",
    },
    [30] = {
        houseId = 30,
        label = "House ON RoxWood County #010",
        price = 1100000,
        door_coords = vector4(-663.8026, 7468.1958, 7.0354, 112.7209),
        garage_coords = vector4(-654.3079, 7477.4014, 6.9731, 98.4352),
        coords_label = "RoxWood County #010",
    },
    [31] = {
        houseId = 31,
        label = "House ON RoxWood County #011",
        price = 1200000,
        door_coords = vector4(-638.7070, 7440.0962, 6.4055, 158.7205),
        garage_coords = vector4(-649.1045, 7449.9341, 6.7921, 149.0405),
        coords_label = "RoxWood County #011",
    },
    [32] = {
        houseId = 32,
        label = "House ON RoxWood County #012",
        price = 600000,
        door_coords = vector4(-612.2147, 7539.8770, 7.7311, 53.8836),
        garage_coords = vector4(-604.1505, 7528.1895, 7.8037, 331.7002),
        coords_label = "RoxWood County #012",
    },
    [33] = {
        houseId = 33,
        label = "House ON RoxWood County #013",
        price = 700000,
        door_coords = vector4(-625.2980, 7503.0259, 6.5434, 343.1587),
        garage_coords = vector4(-633.7324, 7495.1353, 6.7824, 194.2907),
        coords_label = "RoxWood County #013",
    },
    [34] = {
        houseId = 34,
        label = "House ON RoxWood County #014",
        price = 400000,
        door_coords = vector4(-590.9854, 7561.3066, 7.7655, 55.9513),
        garage_coords = vector4(-586.9478, 7548.9038, 7.3238, 54.4562),
        coords_label = "RoxWood County #014",
    },
    [35] = {
        houseId = 35,
        label = "House ON RoxWood County #015",
        price = 720000,
        door_coords = vector4(-574.3384, 7584.3120, 6.8869, 47.6635),
        garage_coords = vector4(-562.7376, 7585.1533, 6.7149, 228.0104),
        coords_label = "RoxWood County #015",
    },
    [36] = {
        houseId = 36,
        label = "House ON RoxWood County #016",
        price = 950000,
        door_coords = vector4(-555.4397, 7604.1162, 7.8649, 46.9995),
        garage_coords = vector4(-553.7408, 7598.0273, 6.6201, 214.0598),
        coords_label = "RoxWood County #016",
    },
}

--[[ House Indicators ]]
Config.Indicators = {
    electricity = {
        unitPrice = 5, -- [[ Unit price at the time of purchase ]]
        maxValue = 1000 --[[ Max value that can be stored ]]
    },
    power = {
        unitPrice = 5,
        maxValue = 1000
    },
    gas = {
        unitPrice = 5,
        maxValue = 1000
    },
    water = {
        unitPrice = 5,
        maxValue = 1000
    },
}

--[[ CCTV ]]
Config.CCTV = {
    Enabled = true,
    MaxZoom = 30,
    MinZoom = 100,
    RotateSpeed = 0.3,
    Controls = {
        ZoomIn = 96,  -- UP Arrow
        ZoomOut = 97, -- DOWN Arrow
        Exit = 194,   -- BACKSPACE
    }
}

--[[ House Wall Colors ]]
Config.WallColors = {
    { id = 1,  color = "#FFDB28" },
    { id = 2,  color = "#FF6F00" },
    { id = 3,  color = "#BF1F19" },
    { id = 4,  color = "#FF2525" },
    { id = 5,  color = "#f5f5dc" },
    { id = 7,  color = "#DDDAD7" },
    { id = 9,  color = "#666666" },
    { id = 13, color = "#0a0403" },
    { id = 15, color = "#AE6E1E" },
    { id = 19, color = "#6d3300" },
    { id = 22, color = "#99821E" },
    { id = 23, color = "#83961E" },
    { id = 24, color = "#6CAA1E" },
    { id = 25, color = "#57BD1E" },
    { id = 26, color = "#00bf5f" },
    { id = 30, color = "#265816" },
    { id = 31, color = "#00C1A7" },
    { id = 33, color = "#40D0BD" },
    { id = 34, color = "#00B5B8" },
    { id = 36, color = "#0494E4" },
    { id = 37, color = "#7338FF" },
    { id = 39, color = "#8131FF" },
    { id = 40, color = "#bf005f" },
}

--[[ Furniture Items ]]
Config.FurnitureItems = {
    ["pixelhouse"] = {
        label = "منزل",
        items = {
            { model = "qua_0r_house_floor",       price = 1000, label = "طابق #1" },
            { model = "qua_0r_house_floor_2",     price = 1000, label = "طابق #2" },
            { model = "qua_0r_house_floor_3",     price = 1000, label = "طابق #3" },
            { model = "qua_0r_house_floor_4",     price = 1000, label = "طابق #4" },
            { model = "qua_0r_house_floor_5",     price = 1000, label = "طابق #5" },
            { model = "qua_0r_house_floor_6",     price = 1000, label = "طابق #6" },
            { model = "qua_0r_house_circlefloor", price = 1000, label = "طابق (دائري)" },
            { model = "qua_0r_house_doorwall",    price = 1000, label = "جدار الباب" },
            { model = "qua_0r_house_wall",        price = 1000, label = "جدار" },
            { model = "qua_0r_house_wall_2",      price = 1000, label = "جدار #2" },
            { model = "qua_0r_house_wall_3",      price = 1000, label = "جدار #3" },
            { model = "qua_0r_house_longwall",    price = 1000, label = "جدار (طويل)" },
            { model = "qua_0r_house_longwall_2",  price = 1000, label = "جدار (طويل) #2" },
            { model = "qua_0r_house_tallwall",    price = 1000, label = "جدار (طويل) #3" },
        },
    },
    ["stashes"] = {
        label = "صناديق التخزين",
        items = {
            [1] = { model = "v_res_tre_storagebox", price = 2500, label = "صندوق تخزين" },
            [2] = { model = "prop_devin_box_closed", price = 2500, label = "صندوق ديفين" },
            [3] = { model = "prop_mil_crate_01", price = 2500, label = "صندوق عسكري 1" },
            [4] = { model = "prop_mil_crate_02", price = 2500, label = "صندوق عسكري 2" },
            [5] = { model = "prop_box_wood05a", price = 2500, label = "صندوق خشبي 5" },
            [6] = { model = "prop_drop_crate_01", price = 2500, label = "صندوق إسقاط 1" },
            [7] = { model = "prop_box_wood02a_pu", price = 2500, label = "صندوق خشبي 2 PU" },
            [8] = { model = "prop_box_wood04a", price = 2500, label = "صندوق خشبي 4" },
            [9] = { model = "prop_crate_07a", price = 2500, label = "صندوق 7" },
            [10] = { model = "prop_mb_crate_01a", price = 2500, label = "صندوق 1" },
        },
    },
    ["wardrobe"] = {
        label = "خزانة الملابس",
        items = {
            [1] = { model = "v_res_tre_wardrobe", price = 2500, label = "خزانة V" },
        },
    },
    ["weed_planter"] = {
        label = "خزانة زراعة القنب",
        items = {
            { model = "qua_weed_planter",       price = 2000, label = "خزانة زراعة القنب" },
            { model = "qua_weed_planter_basic", price = 1000, label = "خزانة زراعة القنب الأساسية" },
        }
    },
    ["weed_dryer"] = {
        label = "مجفف القنب",
        items = {
            { model = "qua_weed_dryer", price = 1000, label = "مجفف القنب" },
        }
    },
    ["weed_heather"] = {
        label = "سخان القنب",
        items = {
            { model = "qua_weed_heather",     price = 1000, label = "سخان القنب #1" },
            { model = "prop_elec_heater_01",  price = 1000, label = "سخان القنب #2" },
            { model = "prop_patio_heater_01", price = 1000, label = "سخان القنب #3" },
        }
    },
    ["weed_light"] = {
        label = "إضاءة القنب",
        items = {
            { model = "prop_wall_light_05a",              price = 1000, label = "إضاءة جدارية" },
            { model = "ch_prop_ch_lamp_ceiling_w_01a",    price = 1000, label = "مصباح سقف" },
            { model = "h4_prop_x17_sub_lampa_small_blue", price = 1000, label = "مصباح صغير أزرق" },
        }
    },
    ["weed_fans"] = {
        label = "مراوح القنب",
        items = {
            { model = "prop_fan_01",       price = 1000, label = "مروحة 01" },
            { model = "v_res_fa_fan",      price = 1000, label = "مروحة FA" },
            { model = "prop_wall_vent_02", price = 1000, label = "مروحة جدارية" },
        }
    },
    ["weed_table"] = {
        label = "طاولة القنب",
        items = {
            { model = "bkr_prop_weed_table_01a", price = 1000, label = "طاولة" },
        }
    },
    ["sofas"] = {
        label = "أرائك",
        items = {
            { model = "miss_rub_couch_01",           price = 300,  label = "أريكة قديمة" },
            { model = "prop_fib_3b_bench",           price = 700,  label = "أريكة ثلاثية" },
            { model = "prop_ld_farm_chair01",        price = 250,  label = "كرسي قديم" },
            { model = "prop_ld_farm_couch01",        price = 300,  label = "أريكة ثلاثية قديمة" },
            { model = "prop_ld_farm_couch02",        price = 300,  label = "أريكة مخططة قديمة" },
            { model = "v_res_d_armchair",            price = 300,  label = "كرسي بمقعد واحد أصفر" },
            { model = "v_res_fh_sofa",               price = 3700, label = "أريكة زاوية" },
            { model = "v_res_mp_sofa",               price = 3700, label = "أريكة زاوية 2" },
            { model = "v_res_d_sofa",                price = 700,  label = "أريكة 1" },
            { model = "v_res_j_sofa",                price = 700,  label = "أريكة 2" },
            { model = "v_res_mp_stripchair",         price = 700,  label = "أريكة 3" },
            { model = "v_res_m_h_sofa_sml",          price = 700,  label = "أريكة 4" },
            { model = "v_res_r_sofa",                price = 700,  label = "أريكة 5" },
            { model = "v_res_tre_sofa",              price = 700,  label = "أريكة 6" },
            { model = "v_res_tre_sofa_mess_a",       price = 700,  label = "أريكة 7" },
            { model = "v_res_tre_sofa_mess_b",       price = 700,  label = "أريكة 8" },
            { model = "v_res_tre_sofa_mess_c",       price = 700,  label = "أريكة 9" },
            { model = "v_res_tt_sofa",               price = 700,  label = "أريكة 10" },
            { model = "prop_rub_couch02",            price = 700,  label = "أريكة 11" },
            { model = "v_ilev_m_sofa",               price = 2000, label = "أريكة بيضاء" },
            { model = "v_med_p_sofa",                price = 1000, label = "أريكة جلدية بنية" },
        }
    },
    ["chairs"] = {
        label = "كراسي",
        items = {
            { model = "prop_tv_flat_01", price = 700, label = "تلفاز ريو" },
            { model = "v_res_d_highchair", price = 700, label = "كرسي مرتفع" },
            { model = "apa_mp_h_stn_chairstrip_03", price = 500, label = "كرسي ستيتش 4" },
            { model = "v_res_fa_chair01", price = 700, label = "كرسي 1" },
            { model = "v_res_fa_chair02", price = 700, label = "كرسي 2" },
            { model = "v_res_fh_barcchair", price = 700, label = "كرسي مرتفع 2" },
            { model = "v_res_fh_dineeamesa", price = 700, label = "كرسي مطبخ 1" },
            { model = "v_res_fh_dineeamesb", price = 700, label = "كرسي مطبخ 2" },
            { model = "v_res_fh_dineeamesc", price = 700, label = "كرسي مطبخ 3" },
            { model = "v_res_fh_easychair", price = 700, label = "كرسي 3" },
            { model = "v_res_fh_kitnstool", price = 700, label = "كرسي 4" },
            { model = "v_res_fh_singleseat", price = 700, label = "كرسي مرتفع 3" },
            { model = "v_res_jarmchair", price = 700, label = "كرسي ذراع" },
            { model = "v_res_j_dinechair", price = 700, label = "كرسي مطبخ 4" },
            { model = "v_res_j_stool", price = 700, label = "كرسي 5" },
            { model = "v_res_mbchair", price = 700, label = "كرسي MB" },
            { model = "v_res_m_armchair", price = 700, label = "كرسي ذراع 2" },
            { model = "v_res_m_dinechair", price = 700, label = "كرسي مطبخ 5" },
            { model = "v_res_study_chair", price = 700, label = "كرسي دراسة" },
            { model = "v_res_trev_framechair", price = 700, label = "إطار كرسي" },
            { model = "v_res_tre_chair", price = 700, label = "كرسي 5" },
            { model = "v_res_tre_officechair", price = 700, label = "كرسي مكتب" },
            { model = "v_res_tre_stool", price = 700, label = "كرسي 6" },
            { model = "v_res_tre_stool_leather", price = 700, label = "كرسي جلد" },
            { model = "v_res_tre_stool_scuz", price = 700, label = "كرسي سكوز" },
            { model = "v_med_p_deskchair", price = 700, label = "كرسي مكتب" },
            { model = "v_med_p_easychair", price = 700, label = "كرسي سهل" },
            { model = "v_med_whickerchair1", price = 700, label = "كرسي ويكر" },
            { model = "prop_direct_chair_01", price = 700, label = "كرسي مباشر" },
            { model = "prop_direct_chair_02", price = 700, label = "كرسي مباشر 2" },
            { model = "prop_yacht_lounger", price = 700, label = "كرسي يخت 1" },
            { model = "prop_yacht_seat_01", price = 700, label = "كرسي يخت 2" },
            { model = "prop_yacht_seat_02", price = 700, label = "كرسي يخت 3" },
            { model = "prop_yacht_seat_03", price = 700, label = "كرسي يخت 4" },
            { model = "v_ret_chair_white", price = 100, label = "كرسي أبيض" },
            { model = "v_ret_chair", price = 100, label = "كرسي 7" },
            { model = "v_ret_ta_stool", price = 100, label = "كرسي TA" },
            { model = "prop_cs_office_chair", price = 100, label = "كرسي مكتب 2" },
            { model = "apa_mp_h_yacht_armchair_01", price = 1000, label = "كرسي فاخر أبيض" },
            { model = "v_club_barchair", price = 300, label = "كرسي 8" },
            { model = "prop_off_chair_04", price = 300, label = "كرسي مكتب 2" },
            { model = "v_club_stagechair", price = 500, label = "كرسي روز" },
            { model = "v_club_officechair", price = 500, label = "كرسي مكتب 3" },
            { model = "prop_armchair_01", price = 500, label = "كرسي جلوس" },
            { model = "prop_bar_stool_01", price = 300, label = "كرسي بار" },
            { model = "apa_mp_h_yacht_stool_01", price = 300, label = "كرسي بار أبيض" },
            { model = "apa_mp_h_stn_chairarm_12", price = 500, label = "كرسي ستيتش 3" },
            { model = "apa_mp_h_stn_chairstool_12", price = 300, label = "دعم الأقدام" },
            { model = "prop_chair_03", price = 100, label = "كرسي خشبي" },
            { model = "prop_couch_sm_05", price = 500, label = "كرسي ذراع مخملي" },
            { model = "prop_couch_sm_07", price = 300, label = "كرسي ذراع أبيض 2" },
            { model = "prop_couch_sm_02", price = 300, label = "كرسي ذراع برتقالي" },
            { model = "apa_mp_h_stn_sofa_daybed_01", price = 500, label = "كرسي صالة" },
            { model = "apa_mp_h_stn_sofa_daybed_02", price = 500, label = "كرسي صالة 2" },
            { model = "apa_mp_h_din_chair_04", price = 500, label = "كرسي حديث" },
            { model = "apa_mp_h_din_chair_08", price = 500, label = "كرسي حديث 2" },
            { model = "apa_mp_h_din_chair_09", price = 500, label = "كرسي حديث 3" },
            { model = "apa_mp_h_din_chair_12", price = 500, label = "كرسي حديث 4" },
            { model = "apa_mp_h_din_stool_04", price = 500, label = "كرسي حديث 5" },
            { model = "apa_mp_h_stn_chairarm_01", price = 500, label = "كرسي حديث 6" },
            { model = "apa_mp_h_stn_chairarm_02", price = 500, label = "كرسي حديث 7" },
            { model = "apa_mp_h_stn_chairarm_03", price = 500, label = "كرسي حديث 8" },
            { model = "apa_mp_h_stn_chairarm_09", price = 500, label = "كرسي حديث 9" },
            { model = "apa_mp_h_stn_chairarm_11", price = 500, label = "كرسي حديث 10" },
            { model = "apa_mp_h_stn_chairarm_13", price = 500, label = "كرسي حديث 11" },
            { model = "apa_mp_h_stn_chairarm_24", price = 500, label = "كرسي حديث 12" },
            { model = "apa_mp_h_stn_chairarm_25", price = 500, label = "كرسي حديث 13" },
            { model = "apa_mp_h_stn_chairarm_26", price = 500, label = "كرسي حديث 14" },
            { model = "apa_mp_h_stn_chairstrip_04", price = 500, label = "كرسي حديث 15" },
            { model = "apa_mp_h_stn_chairstrip_05", price = 500, label = "كرسي حديث 16" },
            { model = "apa_mp_h_stn_chairstrip_08", price = 500, label = "كرسي حديث 17" },
            { model = "apa_mp_h_stn_chairstrip_09", price = 500, label = "كرسي حديث 18" },
            { model = "apa_mp_h_stn_chairstrip_10", price = 500, label = "كرسي حديث 19" },
            { model = "apa_mp_h_stn_chairstrip_11", price = 500, label = "كرسي حديث 20" },
            { model = "apa_mp_h_stn_chairstrip_13", price = 500, label = "كرسي حديث 21" },
            { model = "apa_mp_h_stn_chairstrip_14", price = 500, label = "كرسي حديث 22" },
            { model = "apa_mp_h_stn_chairstrip_15", price = 500, label = "كرسي حديث 23" },
            { model = "apa_mp_h_stn_chairstrip_16", price = 500, label = "كرسي حديث 24" },
            { model = "apa_mp_h_stn_chairstrip_17", price = 500, label = "كرسي حديث 25" },
            { model = "apa_mp_h_stn_chairstrip_18", price = 500, label = "كرسي حديث 26" },
            { model = "apa_mp_h_stn_chairstrip_19", price = 500, label = "كرسي حديث 27" },
            { model = "apa_mp_h_stn_chairstrip_20", price = 500, label = "كرسي حديث 28" },
            { model = "apa_mp_h_stn_chairstrip_21", price = 500, label = "كرسي حديث 29" },
            { model = "apa_mp_h_stn_chairstrip_22", price = 500, label = "كرسي حديث 30" },
            { model = "apa_mp_h_stn_chairstrip_23", price = 500, label = "كرسي حديث 31" },
            { model = "apa_mp_h_stn_chairstrip_24", price = 500, label = "كرسي حديث 32" },
            { model = "apa_mp_h_stn_chairstrip_25", price = 500, label = "كرسي حديث 33" },
            { model = "apa_mp_h_stn_chairstrip_26", price = 500, label = "كرسي حديث 34" },
            { model = "apa_mp_h_stn_chairstrip_27", price = 500, label = "كرسي حديث 35" },
            { model = "apa_mp_h_stn_chairstrip_28", price = 500, label = "كرسي حديث 36" },
            { model = "apa_mp_h_stn_chairstrip_29", price = 500, label = "كرسي حديث 37" },
            { model = "apa_mp_h_stn_chairstrip_30", price = 500, label = "كرسي حديث 38" },
            { model = "apa_mp_h_stn_chairstrip_31", price = 500, label = "كرسي حديث 39" },
            { model = "apa_mp_h_stn_chairstrip_32", price = 500, label = "كرسي حديث 40" },
            { model = "apa_mp_h_stn_chairstrip_33", price = 500, label = "كرسي حديث 41" },
            { model = "apa_mp_h_stn_chairstrip_34", price = 500, label = "كرسي حديث 42" },
            { model = "apa_mp_h_stn_chairstrip_35", price = 500, label = "كرسي حديث 43" },
            { model = "apa_mp_h_stn_chairstrip_36", price = 500, label = "كرسي حديث 44" },
            { model = "apa_mp_h_stn_chairstrip_37", price = 500, label = "كرسي حديث 45" },
            { model = "apa_mp_h_stn_chairstrip_38", price = 500, label = "كرسي حديث 46" },
            { model = "apa_mp_h_stn_chairstrip_39", price = 500, label = "كرسي حديث 47" },
            { model = "apa_mp_h_stn_chairstrip_40", price = 500, label = "كرسي حديث 48" },
            { model = "apa_mp_h_stn_chairstrip_41", price = 500, label = "كرسي حديث 49" },
            { model = "apa_mp_h_stn_chairstrip_42", price = 500, label = "كرسي حديث 50" },
            { model = "apa_mp_h_stn_chairstrip_43", price = 500, label = "كرسي حديث 51" },
            { model = "apa_mp_h_stn_chairstrip_44", price = 500, label = "كرسي حديث 52" },
            { model = "apa_mp_h_stn_chairstrip_45", price = 500, label = "كرسي حديث 53" },
            { model = "apa_mp_h_stn_chairstrip_46", price = 500, label = "كرسي حديث 54" },
            { model = "apa_mp_h_stn_chairstrip_47", price = 500, label = "كرسي حديث 55" },
            { model = "apa_mp_h_stn_chairstrip_48", price = 500, label = "كرسي حديث 56" },
            { model = "apa_mp_h_stn_chairstrip_49", price = 500, label = "كرسي حديث 57" },
            { model = "apa_mp_h_stn_chairstrip_50", price = 500, label = "كرسي حديث 58" },
            { model = "apa_mp_h_stn_chairstrip_51", price = 500, label = "كرسي حديث 59" },
            { model = "apa_mp_h_stn_chairstrip_52", price = 500, label = "كرسي حديث 60" },
            { model = "apa_mp_h_stn_chairstrip_53", price = 500, label = "كرسي حديث 61" },
            { model = "apa_mp_h_stn_chairstrip_54", price = 500, label = "كرسي حديث 62" },
            { model = "apa_mp_h_stn_chairstrip_55", price = 500, label = "كرسي حديث 63" },
            { model = "apa_mp_h_stn_chairstrip_56", price = 500, label = "كرسي حديث 64" },
            { model = "apa_mp_h_stn_chairstrip_57", price = 500, label = "كرسي حديث 65" },
            { model = "apa_mp_h_stn_chairstrip_58", price = 500, label = "كرسي حديث 66" },
            { model = "apa_mp_h_stn_chairstrip_59", price = 500, label = "كرسي حديث 67" },
            { model = "apa_mp_h_stn_chairstrip_60", price = 500, label = "كرسي حديث 68" },
            { model = "apa_mp_h_stn_chairstrip_61", price = 500, label = "كرسي حديث 69" },
            { model = "apa_mp_h_stn_chairstrip_62", price = 500, label = "كرسي حديث 70" },
            { model = "apa_mp_h_stn_chairstrip_63", price = 500, label = "كرسي حديث 71" },
            { model = "apa_mp_h_stn_chairstrip_64", price = 500, label = "كرسي حديث 72" },
            { model = "apa_mp_h_stn_chairstrip_65", price = 500, label = "كرسي حديث 73" },
            { model = "apa_mp_h_stn_chairstrip_66", price = 500, label = "كرسي حديث 74" },
            { model = "apa_mp_h_stn_chairstrip_67", price = 500, label = "كرسي حديث 75" },
            { model = "apa_mp_h_stn_chairstrip_68", price = 500, label = "كرسي حديث 76" },
            { model = "apa_mp_h_stn_chairstrip_69", price = 500, label = "كرسي حديث 77" },
            { model = "apa_mp_h_stn_chairstrip_70", price = 500, label = "كرسي حديث 78" },
            { model = "apa_mp_h_stn_chairstrip_71", price = 500, label = "كرسي حديث 79" },
            { model = "apa_mp_h_stn_chairstrip_72", price = 500, label = "كرسي حديث 80" },
            { model = "apa_mp_h_stn_chairstrip_73", price = 500, label = "كرسي حديث 81" },
            { model = "apa_mp_h_stn_chairstrip_74", price = 500, label = "كرسي حديث 82" },
            { model = "apa_mp_h_stn_chairstrip_75", price = 500, label = "كرسي حديث 83" },
            { model = "apa_mp_h_stn_chairstrip_76", price = 500, label = "كرسي حديث 84" },
            { model = "apa_mp_h_stn_chairstrip_77", price = 500, label = "كرسي حديث 85" },
            { model = "apa_mp_h_stn_chairstrip_78", price = 500, label = "كرسي حديث 86" },
            { model = "apa_mp_h_stn_chairstrip_79", price = 500, label = "كرسي حديث 87" },
            { model = "apa_mp_h_stn_chairstrip_80", price = 500, label = "كرسي حديث 88" },
            { model = "apa_mp_h_stn_chairstrip_81", price = 500, label = "كرسي حديث 89" },
            { model = "apa_mp_h_stn_chairstrip_82", price = 500, label = "كرسي حديث 90" },
            { model = "apa_mp_h_stn_chairstrip_83", price = 500, label = "كرسي حديث 91" },
            { model = "apa_mp_h_stn_chairstrip_84", price = 500, label = "كرسي حديث 92" },
            { model = "apa_mp_h_stn_chairstrip_85", price = 500, label = "كرسي حديث 93" },
            { model = "apa_mp_h_stn_chairstrip_86", price = 500, label = "كرسي حديث 94" },
            { model = "apa_mp_h_stn_chairstrip_87", price = 500, label = "كرسي حديث 95" },
            { model = "apa_mp_h_stn_chairstrip_88", price = 500, label = "كرسي حديث 96" },
            { model = "apa_mp_h_stn_chairstrip_89", price = 500, label = "كرسي حديث 97" },
            { model = "apa_mp_h_stn_chairstrip_90", price = 500, label = "كرسي حديث 98" },
            { model = "apa_mp_h_stn_chairstrip_91", price = 500, label = "كرسي حديث 99" },
            { model = "apa_mp_h_stn_chairstrip_92", price = 500, label = "كرسي حديث 100" },
            { model = "apa_mp_h_stn_chairstrip_93", price = 500, label = "كرسي حديث 101" },
            { model = "apa_mp_h_stn_chairstrip_94", price = 500, label = "كرسي حديث 102" },
            { model = "apa_mp_h_stn_chairstrip_95", price = 500, label = "كرسي حديث 103" },
            { model = "apa_mp_h_stn_chairstrip_96", price = 500, label = "كرسي حديث 104" },
            { model = "apa_mp_h_stn_chairstrip_97", price = 500, label = "كرسي حديث 105" },
            { model = "apa_mp_h_stn_chairstrip_98", price = 500, label = "كرسي حديث 106" },
            { model = "apa_mp_h_stn_chairstrip_99", price = 500, label = "كرسي حديث 107" },
            { model = "apa_mp_h_stn_chairstrip_100", price = 500, label = "كرسي حديث 108" },
        },
    },
    ["beds"] = {
        label = "أسرة",
        items = {
            { model = "v_res_d_bed",                price = 700,  label = "سرير 1" },
            { model = "v_res_lestersbed",           price = 700,  label = "سرير 2" },
            { model = "v_res_mbbed",                price = 700,  label = "سرير MB" },
            { model = "v_res_mdbed",                price = 700,  label = "سرير MD" },
            { model = "v_res_msonbed",              price = 700,  label = "سرير 3" },
            { model = "v_res_tre_bed1",             price = 700,  label = "سرير 4" },
            { model = "v_res_tre_bed2",             price = 700,  label = "سرير T" },
            { model = "v_res_tt_bed",               price = 700,  label = "سرير TT" },
            { model = "apa_mp_h_bed_with_table_02", price = 5000, label = "سرير فاخر" },
            { model = "apa_mp_h_bed_wide_05",       price = 5000, label = "سرير أحمر" },
            { model = "apa_mp_h_bed_double_08",     price = 3000, label = "سرير مربع" },
            { model = "apa_mp_h_bed_double_09",     price = 3000, label = "سرير حديث" },
            { model = "apa_mp_h_yacht_bed_01",      price = 5000, label = "سرير كاليفورنيا كينغ" },
            { model = "apa_mp_h_yacht_bed_02",      price = 5000, label = "سرير كاليفورنيا كينغ 2" },
            { model = "bkr_prop_biker_campbed_01",  price = 100,  label = "سرير تخييم" },
            { model = "ex_prop_exec_bed_01",        price = 700,  label = "سرير صغير" },
            { model = "gr_prop_bunker_bed_01",      price = 700,  label = "سرير كيلين 2" },
            { model = "p_mbbed_s",                  price = 700,  label = "سرير 5" }
        },
    },
    
    ["general"] = {
        label = "أغراض عامة",
        items = {
            { model = "v_corp_facebeanbag",       price = 100,  label = "كرسي بذور 1" },
            { model = "v_res_cherubvase",         price = 2500, label = "مزهرية بيضاء" },
            { model = "v_res_d_paddedwall",       price = 300,  label = "جدار مبطن" },
            { model = "v_res_d_ramskull",         price = 300,  label = "عنصر" },
            { model = "v_res_d_whips",            price = 300,  label = "سلاسل" },
            { model = "v_res_fashmag1",           price = 300,  label = "مجلات" },
            { model = "v_res_fashmagopen",        price = 300,  label = "مجلات مفتوحة" },
            { model = "v_res_fa_magtidy",         price = 300,  label = "تخزين مجلات" },
            { model = "v_res_fa_yogamat002",      price = 300,  label = "سجادة يوغا 1" },
            { model = "v_res_fa_yogamat1",        price = 300,  label = "سجادة يوغا 2" },
            { model = "v_res_fh_aftershavebox",   price = 300,  label = "عطر" },
            { model = "v_res_fh_flowersa",        price = 300,  label = "زهور" },
            { model = "v_res_fh_fruitbowl",       price = 300,  label = "طبق فواكه" },
            { model = "v_res_fh_laundrybasket",   price = 300,  label = "سلة غسيل" },
            { model = "v_res_fh_pouf",            price = 300,  label = "وسادة" },
            { model = "v_res_fh_sculptmod",       price = 300,  label = "تمثال" },
            { model = "v_res_j_magrack",          price = 300,  label = "رف مجلات" },
            { model = "v_res_jewelbox",           price = 300,  label = "صندوق مجوهرات" },
            { model = "v_res_mbbin",              price = 300,  label = "سلة" },
            { model = "v_res_mbowlornate",        price = 300,  label = "وعاء مزخرف" },
            { model = "v_res_mbronzvase",         price = 300,  label = "مزهرية برونزية" },
            { model = "v_res_mchalkbrd",          price = 300,  label = "لوح شائكة" },
            { model = "v_res_mddresser",          price = 300,  label = "خزانة" },
            { model = "v_res_mplinth",            price = 300,  label = "قائمة" },
            { model = "v_res_mp_ashtrayb",        price = 300,  label = "منفضة سجائر" },
            { model = "v_res_m_candle",           price = 300,  label = "شمعة" },
            { model = "v_res_m_candlelrg",        price = 300,  label = "شمعة كبيرة" },
            { model = "v_res_m_kscales",          price = 300,  label = "ميزان" },
            { model = "v_res_tt_bedpillow",       price = 300,  label = "وسادة سرير" },
            { model = "v_med_cor_whiteboard",     price = 300,  label = "لوح أبيض" },
            { model = "prop_ashtray_01",          price = 100,  label = "منفضة سجائر سوداء" },
            { model = "v_ret_fh_ashtray",         price = 100,  label = "منفضة سجائر حجرية" },
            { model = "v_24_wdr_mesh_rugs",       price = 500,  label = "سجادة" },
            { model = "apa_mp_h_acc_rugwooll_04", price = 500,  label = "سجادة 2" },
            { model = "ex_mp_h_acc_rugwoolm_04",  price = 500,  label = "سجادة 3" },
            { model = "apa_mp_h_acc_rugwoolm_03", price = 500,  label = "سجادة 4" },
            { model = "apa_mp_h_acc_rugwooll_03", price = 500,  label = "سجادة 5" },
            { model = "apa_mp_h_acc_rugwoolm_04", price = 500,  label = "سجادة 6" },
            { model = "v_club_rack",              price = 500,  label = "رف ملابس" }
        },
    },
    
    ["general2"] = {
        label = "الأشياء",
        items = {
            { model = "prop_a4_pile_01",               price = 100, label = "كومة A4" },
            { model = "prop_amb_40oz_03",              price = 100, label = "40 أونصة" },
            { model = "prop_amb_beer_bottle",          price = 100, label = "زجاجة بيرة" },
            { model = "prop_aviators_01",              price = 100, label = "نظارات شمسية" },
            { model = "prop_barry_table_detail",       price = 100, label = "تفاصيل" },
            { model = "prop_beer_box_01",              price = 100, label = "صندوق بيرة" },
            { model = "prop_binoc_01",                 price = 100, label = "منظار" },
            { model = "prop_blox_spray",               price = 100, label = "بخاخ" },
            { model = "prop_bongos_01",                price = 100, label = "بونغوس" },
            { model = "prop_bong_01",                  price = 100, label = "بونغ" },
            { model = "prop_boombox_01",               price = 100, label = "مكبر صوت" },
            { model = "prop_bowl_crisps",              price = 100, label = "وعاء رقائق" },
            { model = "prop_candy_pqs",                price = 100, label = "حلوى" },
            { model = "prop_carrier_bag_01",           price = 100, label = "حقيبة" },
            { model = "prop_ceramic_jug_01",           price = 100, label = "إبريق خزفي" },
            { model = "prop_cigar_pack_01",            price = 100, label = "عبوة سيجار 1" },
            { model = "prop_cigar_pack_02",            price = 100, label = "عبوة سيجار 2" },
            { model = "prop_cs_beer_box",              price = 100, label = "صندوق بيرة 2" },
            { model = "prop_cs_binder_01",             price = 100, label = "مجلد" },
            { model = "prop_cs_bs_cup",                price = 100, label = "كوب" },
            { model = "prop_cs_cashenvelope",          price = 100, label = "ظرف" },
            { model = "prop_cs_champ_flute",           price = 100, label = "كأس شمبانيا" },
            { model = "prop_cs_duffel_01",             price = 100, label = "حقيبة دفل" },
            { model = "prop_cs_dvd",                   price = 50,  label = "قرص DVD" },
            { model = "prop_cs_dvd_case",              price = 50,  label = "حافظة DVD" },
            { model = "prop_cs_film_reel_01",          price = 100, label = "لفة فيلم" },
            { model = "prop_cs_ilev_blind_01",         price = 100, label = "ستارة" },
            { model = "p_ld_bs_bag_01",                price = 100, label = "حقيبة" },
            { model = "prop_cs_ironing_board",         price = 100, label = "لوح الكي" },
            { model = "prop_cs_katana_01",             price = 100, label = "كاتانا" },
            { model = "prop_cs_kettle_01",             price = 100, label = "غلاية" },
            { model = "prop_cs_lester_crate",          price = 100, label = "صندوق" },
            { model = "prop_cs_petrol_can",            price = 100, label = "عبوة بنزين" },
            { model = "prop_cs_sack_01",               price = 100, label = "كيس" },
            { model = "prop_cs_script_bottle_01",      price = 100, label = "زجاجة سكربت" },
            { model = "prop_cs_script_bottle",         price = 100, label = "زجاجة سكربت 2" },
            { model = "prop_cs_street_binbag_01",      price = 100, label = "كيس القمامة" },
            { model = "prop_cs_whiskey_bottle",        price = 100, label = "زجاجة ويسكي" },
            { model = "prop_sh_bong_01",               price = 100, label = "بونغ" },
            { model = "prop_peanut_bowl_01",           price = 100, label = "فول سوداني" },
            { model = "prop_tumbler_01",               price = 100, label = "كأس" },
            { model = "prop_weed_bottle",              price = 100, label = "زجاجة حشيش" },
            { model = "p_cs_lighter_01",               price = 100, label = "ولاعة" },
            { model = "p_cs_papers_01",                price = 100, label = "ورق لف" },
            { model = "v_res_d_dildo_f",               price = 100, label = "ديلدو أسود" },
            { model = "v_res_d_dildo_c",               price = 100, label = "ديلدو أبيض" },
            { model = "v_res_d_dildo_a",               price = 100, label = "لعبة ماما" },
            { model = "prop_champ_cool",               price = 100, label = "مبرد شمبانيا" },
            { model = "prop_champ_01b",                price = 100, label = "زجاجة شمبانيا" },
            { model = "prop_champ_flute",              price = 100, label = "كأس شمبانيا" },
            { model = "ba_prop_club_champset",         price = 300, label = "طقم شمبانيا" },
            { model = "v_res_fa_candle01",             price = 100, label = "شمعة زرقاء" },
            { model = "v_res_fa_candle02",             price = 100, label = "شمعة حمراء" },
            { model = "v_res_fa_candle03",             price = 100, label = "شمعة سوداء" },
            { model = "v_res_fa_candle04",             price = 100, label = "شمعة صغيرة" },
            { model = "v_med_bottles2",                price = 100, label = "مواد كيميائية" },
            { model = "v_res_desktidy",                price = 100, label = "أشياء مكتبية" },
            { model = "v_med_p_notebook",              price = 100, label = "دفتر ملاحظات" },
            { model = "bkr_prop_weed_dry_01a",         price = 100, label = "جبل من الحشيش" },
            { model = "ba_prop_battle_trophy_battler", price = 100, label = "كأس يد" },
            { model = "ba_prop_battle_trophy_no1",     price = 100, label = "كأس نجمة" },
            { model = "prop_golf_bag_01c",             price = 100, label = "حقيبة جولف" },
            { model = "hei_heist_kit_bin_01",          price = 100, label = "سلة قمامة" },
            { model = "prop_wooden_barrel",            price = 100, label = "برميل خشبي" },
            { model = "bkr_prop_bkr_cash_scatter_01",  price = 100, label = "نقود مبعثرة" },
            { model = "bkr_prop_bkr_cashpile_01",      price = 100, label = "نقود" },
            { model = "bkr_prop_bkr_cash_roll_01",     price = 100, label = "لفة نقود" },
            { model = "bkr_prop_bkr_cashpile_04",      price = 100, label = "كومة نقود" },
            { model = "bkr_prop_weed_bigbag_open_01a", price = 100, label = "كيس حشيش مفتوح" },
            { model = "bkr_prop_weed_bigbag_02a",      price = 100, label = "كيس حشيش 2" },
            { model = "bkr_prop_weed_bigbag_03a",      price = 100, label = "كيس حشيش 3" },
            { model = "bkr_prop_weed_scales_01a",      price = 100, label = "ميزان" },
            { model = "bkr_prop_weed_smallbag_01a",    price = 100, label = "كيس حشيش صغير" },
            { model = "bkr_prop_weed_smallbag_02a",    price = 100, label = "كيس حشيش صغير 2" },
            { model = "bkr_prop_weed_smallbag_03a",    price = 100, label = "كيس حشيش صغير 3" },
            { model = "bkr_prop_weed_smallbag_04a",    price = 100, label = "كيس حشيش صغير 4" },
            { model = "bkr_prop_bkr_cashpile_02",      price = 100, label = "كومة نقود 2" },
            { model = "bkr_prop_bkr_cashpile_03",      price = 100, label = "كومة نقود 3" },
        },
    },
    ["general3"] = {
        label = "عشوائي",
        items = {
            { model = "v_ret_csr_bin",            price = 100,  label = "سلة CSR" },
            { model = "v_ret_fh_wickbskt",        price = 100,  label = "سلة" },
            { model = "v_ret_gc_bag01",           price = 100,  label = "حقيبة GC 1" },
            { model = "v_ret_gc_bag02",           price = 100,  label = "حقيبة GC 2" },
            { model = "v_ret_gc_bin",             price = 100,  label = "سلة GC" },
            { model = "v_ret_gc_cashreg",         price = 100,  label = "سجل النقد" },
            { model = "v_ret_gc_chair01",         price = 100,  label = "كرسي GC 01" },
            { model = "v_ret_gc_chair02",         price = 100,  label = "كرسي GC 02" },
            { model = "v_ret_gc_clock",           price = 100,  label = "ساعة" },
            { model = "v_ret_hd_prod1_",          price = 100,  label = "منتج 1" },
            { model = "v_ret_hd_prod2_",          price = 100,  label = "منتج 2" },
            { model = "v_ret_hd_prod3_",          price = 100,  label = "منتج 3" },
            { model = "v_ret_hd_prod4_",          price = 100,  label = "منتج 4" },
            { model = "v_ret_hd_prod5_",          price = 100,  label = "منتج 5" },
            { model = "v_ret_hd_prod6_",          price = 100,  label = "منتج 6" },
            { model = "v_ret_hd_unit1_",          price = 100,  label = "وحدة HD 1" },
            { model = "v_ret_hd_unit2_",          price = 100,  label = "وحدة HD 2" },
            { model = "v_ret_ml_fridge02",        price = 100,  label = "ثلاجة" },
            { model = "v_ret_ps_bag_01",          price = 100,  label = "حقيبة 1" },
            { model = "v_ret_ps_bag_02",          price = 100,  label = "حقيبة 2" },
            { model = "v_ret_ta_book1",           price = 100,  label = "كتاب 1" },
            { model = "v_ret_ta_book2",           price = 100,  label = "كتاب 2" },
            { model = "v_ret_ta_book3",           price = 100,  label = "كتاب 3" },
            { model = "v_ret_ta_book4",           price = 100,  label = "كتاب 4" },
            { model = "v_ret_ta_camera",          price = 100,  label = "كاميرا" },
            { model = "v_ret_ta_firstaid",        price = 100,  label = "إسعاف أولي" },
            { model = "v_ret_ta_hero",            price = 100,  label = "بطل" },
            { model = "v_ret_ta_mag1",            price = 100,  label = "مجلة 1" },
            { model = "v_ret_ta_mag2",            price = 100,  label = "مجلة 2" },
            { model = "v_ret_ta_skull",           price = 100,  label = "جمجمة" },
            { model = "prop_acc_guitar_01",       price = 100,  label = "غيتار" },
            { model = "prop_amb_handbag_01",      price = 100,  label = "حقيبة يد" },
            { model = "prop_attache_case_01",     price = 100,  label = "حقيبة" },
            { model = "prop_big_bag_01",          price = 100,  label = "حقيبة كبيرة" },
            { model = "prop_bonesaw",             price = 100,  label = "منشار العظام" },
            { model = "prop_cs_fertilizer",       price = 100,  label = "سماد" },
            { model = "prop_cs_shopping_bag",     price = 100,  label = "حقيبة تسوق" },
            { model = "prop_cs_vial_01",          price = 100,  label = "قنينة" },
            { model = "prop_defilied_ragdoll_01", price = 100,  label = "دميه" },
            { model = "v_res_fa_book03",          price = 100,  label = "كتاب الكاماسوترا" },
            { model = "prop_weight_rack_02",      price = 500,  label = "رف الأثقال" },
            { model = "prop_weight_bench_02",     price = 500,  label = "طاولة الضغط" },
            { model = "prop_tool_broom",          price = 100,  label = "مقشة" },
            { model = "prop_fire_exting_2a",      price = 100,  label = "طفاية حريق" },
            { model = "v_res_vacuum",             price = 100,  label = "مكنسة كهربائية" },
            { model = "v_ret_gc_fan",             price = 100,  label = "مروحة" },
            { model = "prop_paint_stepl01b",      price = 100,  label = "سلم" },
            { model = "bkr_prop_weed_bucket_01b", price = 100,  label = "سماد" },
            { model = "v_club_vusnaketank",       price = 500,  label = "تيراريوم" },
            { model = "prop_pooltable_02",        price = 1500, label = "طاولة بولينغ" },
            { model = "prop_pool_rack_02",        price = 100,  label = "عصي بولينغ" },
            { model = "v_club_vu_deckcase",       price = 1000, label = "مجموعة DJ" },
            { model = "v_corp_servercln",         price = 1000, label = "رف الخوادم" },    
        },
    },
    ["general4"] = {
        label = "عشوائي 2",
        items = {
            { model = "prop_dummy_01",             price = 100, label = "دمية" },
            { model = "prop_egg_clock_01",         price = 100, label = "ساعة بيض" },
            { model = "prop_el_guitar_01",         price = 100, label = "غيتار كهربائي 1" },
            { model = "prop_el_guitar_02",         price = 100, label = "غيتار كهربائي 2" },
            { model = "prop_el_guitar_03",         price = 100, label = "غيتار كهربائي 3" },
            { model = "prop_feed_sack_01",         price = 100, label = "كيس علف" },
            { model = "prop_floor_duster_01",      price = 100, label = "منظف الأرضية" },
            { model = "prop_fruit_basket",         price = 100, label = "سلة فواكه" },
            { model = "prop_f_duster_02",          price = 100, label = "منظف" },
            { model = "prop_grapes_02",            price = 100, label = "عنب" },
            { model = "prop_hotel_clock_01",       price = 100, label = "ساعة فندق" },
            { model = "prop_idol_case_01",         price = 100, label = "حقيبة تمثال" },
            { model = "prop_jewel_02a",            price = 100, label = "مجموعة مجوهرات" },
            { model = "prop_jewel_02b",            price = 100, label = "مجموعة مجوهرات" },
            { model = "prop_jewel_02c",            price = 100, label = "مجموعة مجوهرات" },
            { model = "prop_jewel_03a",            price = 100, label = "مجموعة مجوهرات" },
            { model = "prop_jewel_03b",            price = 100, label = "مجموعة مجوهرات" },
            { model = "prop_jewel_04a",            price = 100, label = "مجموعة مجوهرات" },
            { model = "prop_jewel_04b",            price = 100, label = "مجموعة مجوهرات" },
            { model = "prop_j_disptray_01",        price = 100, label = "صينية عرض" },
            { model = "prop_j_disptray_01b",       price = 100, label = "صينية عرض" },
            { model = "prop_j_disptray_02",        price = 100, label = "صينية عرض" },
            { model = "prop_j_disptray_03",        price = 100, label = "صينية عرض" },
            { model = "prop_j_disptray_04",        price = 100, label = "صينية عرض" },
            { model = "prop_j_disptray_04b",       price = 100, label = "صينية عرض" },
            { model = "prop_j_disptray_05",        price = 100, label = "صينية عرض" },
            { model = "prop_j_disptray_05b",       price = 100, label = "صينية عرض" },
            { model = "prop_ld_greenscreen_01",    price = 100, label = "شاشة خضراء" },
            { model = "prop_ld_handbag",           price = 100, label = "حقيبة يد" },
            { model = "prop_ld_jerrycan_01",       price = 100, label = "علبة بنزين" },
            { model = "prop_ld_keypad_01",         price = 100, label = "لوحة مفاتيح 1" },
            { model = "prop_ld_keypad_01b",        price = 100, label = "لوحة مفاتيح 2" },
            { model = "prop_ld_suitcase_01",       price = 100, label = "حقيبة 1" },
            { model = "prop_ld_suitcase_02",       price = 100, label = "حقيبة 2" },
            { model = "hei_p_attache_case_shut",   price = 100, label = "حقيبة 3" },
            { model = "prop_mr_rasberryclean",     price = 100, label = "تنظيف توت" },
            { model = "prop_paper_bag_01",         price = 100, label = "حقيبة ورقية" },
            { model = "prop_shopping_bags01",      price = 100, label = "أكياس تسوق" },
            { model = "prop_shopping_bags02",      price = 100, label = "أكياس تسوق 2" },
            { model = "prop_yoga_mat_01",          price = 100, label = "حصيرة يوجا 1" },
            { model = "prop_yoga_mat_02",          price = 100, label = "حصيرة يوجا 2" },
            { model = "prop_yoga_mat_03",          price = 100, label = "حصيرة يوجا 3" },
            { model = "p_ld_sax",                  price = 100, label = "ساكس" },
            { model = "p_ld_soc_ball_01",          price = 100, label = "كرة قدم" },
            { model = "p_watch_01",                price = 100, label = "ساعة 1" },
            { model = "p_watch_02",                price = 100, label = "ساعة 2" },
            { model = "p_watch_03",                price = 100, label = "ساعة 3" },
            { model = "p_watch_04",                price = 100, label = "ساعة 4" },
            { model = "p_watch_05",                price = 100, label = "ساعة 5" },
            { model = "p_watch_06",                price = 100, label = "ساعة 6" },
            { model = "apa_mp_h_acc_candles_01",   price = 100, label = "شمعة" },
            { model = "apa_mp_h_acc_candles_02",   price = 100, label = "شمعة 2" },
            { model = "apa_mp_h_acc_candles_04",   price = 100, label = "شمعة 3" },
            { model = "apa_mp_h_acc_candles_06",   price = 100, label = "شمعة 4" },
            { model = "apa_mp_h_acc_fruitbowl_02", price = 100, label = "وعاء فواكه" },
            { model = "apa_mp_h_acc_tray_01",      price = 100, label = "أشياء صغيرة" },
            { model = "prop_bskball_01",           price = 100, label = "كرة سلة" },
            { model = "prop_cs_wrench",            price = 100, label = "مفتاح ربط" },
            { model = "prop_cs_bowie_knife",       price = 100, label = "خنجر" },
            { model = "prop_w_me_hatchet",         price = 100, label = "فأس" }
        },
    },    
    ["small"] = {
        label = "تفاصيل",
        items = {
            { model = "v_res_r_figcat",               price = 300, label = "تمثال قطة" },
            { model = "v_res_r_figclown",             price = 300, label = "تمثال مهرج" },
            { model = "v_res_r_figauth2",             price = 300, label = "تمثال مؤلف" },
            { model = "v_res_r_figfemale",            price = 300, label = "تمثال أنثى" },
            { model = "v_res_r_figflamenco",          price = 300, label = "تمثال فلامنكو" },
            { model = "v_res_r_figgirl",              price = 300, label = "تمثال فتاة" },
            { model = "v_res_r_figgirlclown",         price = 300, label = "تمثال فتاة مهرج" },
            { model = "v_res_r_figoblisk",            price = 300, label = "تمثال عمودي" },
            { model = "v_res_r_figpillar",            price = 300, label = "تمثال عمود" },
            { model = "v_res_r_teapot",               price = 300, label = "إبريق شاي" },
            { model = "v_res_sculpt_dec",             price = 300, label = "تمثال 1" },
            { model = "v_res_sculpt_decd",            price = 300, label = "تمثال 2" },
            { model = "v_res_sculpt_dece",            price = 300, label = "تمثال 3" },
            { model = "v_res_sculpt_decf",            price = 300, label = "تمثال 4" },
            { model = "v_res_skateboard",             price = 300, label = "لوح تزلج" },
            { model = "v_res_sketchpad",              price = 300, label = "دفتر رسم" },
            { model = "v_res_tissues",                price = 300, label = "مناديل" },
            { model = "v_res_tre_basketmess",         price = 300, label = "سلة" },
            { model = "v_res_tre_bin",                price = 300, label = "سلة قمامة" },
            { model = "v_res_tre_cushiona",           price = 300, label = "وسادة 1" },
            { model = "v_res_tre_cushionb",           price = 300, label = "وسادة 2" },
            { model = "v_res_tre_cushionc",           price = 300, label = "وسادة 3" },
            { model = "v_res_tre_cushiond",           price = 300, label = "وسادة 4" },
            { model = "v_res_tre_cushnscuzb",         price = 300, label = "وسادة 5" },
            { model = "v_res_tre_cushnscuzd",         price = 300, label = "وسادة 6" },
            { model = "v_res_tre_fruitbowl",          price = 300, label = "سلّة فواكه" },
            { model = "v_med_p_sideboard",            price = 300, label = "خزانة جانبية" },
            { model = "prop_idol_01",                 price = 100, label = "تمثال 1" },
            { model = "v_res_r_fighorsestnd",         price = 300, label = "تمثال حصان أسود" },
            { model = "v_res_r_fighorse",             price = 300, label = "تمثال حصان كبير" },
            { model = "v_res_r_figdancer",            price = 300, label = "تمثال راقصة" },
            { model = "v_res_fa_idol02",              price = 300, label = "تمثال فيل" },
            { model = "v_res_m_statue",               price = 300, label = "تمثال" },
            { model = "v_20_ornaeagle",               price = 300, label = "تمثال نسر" },
            { model = "v_med_p_vaseround",            price = 300, label = "مزهرية مستديرة" },
            { model = "ex_mp_h_acc_vase_05",          price = 300, label = "مزهرية بنفسجية" },
            { model = "apa_mp_h_acc_dec_head_01",     price = 300, label = "عمل فني" },
            { model = "apa_mp_h_acc_dec_sculpt_02",   price = 300, label = "عمل فني 2" },
            { model = "ex_mp_h_acc_dec_plate_02",     price = 300, label = "عمل فني 3" },
            { model = "apa_mp_h_acc_bowl_ceramic_01", price = 300, label = "وعاء خزفي" },
            { model = "apa_mp_h_acc_dec_plate_01",    price = 300, label = "طبق 2" },
            { model = "apa_mp_h_acc_vase_01",         price = 300, label = "مزهرية بالأبيض والأسود" },
            { model = "apa_mp_h_acc_vase_02",         price = 300, label = "مزهرية حمراء" },
            { model = "apa_mp_h_acc_vase_05",         price = 300, label = "مزهرية" },
            { model = "apa_mp_h_acc_vase_06",         price = 300, label = "مزهرية بالأبيض والأسود 2" }
        },
    },
    ["electronics"] = {
        label = "إلكترونيات",
        items = {
            { model = "prop_trailr_fridge",                price = 300,  label = "ثلاجة قديمة" },
            { model = "v_res_fh_speaker",                  price = 300,  label = "مكبر صوت" },
            { model = "v_res_fh_speakerdock",              price = 300,  label = "قاعدة مكبر الصوت" },
            { model = "v_res_fh_bedsideclock",             price = 300,  label = "ساعة سرير" },
            { model = "v_res_fa_phone",                    price = 300,  label = "هاتف" },
            { model = "v_res_lest_bigscreen",              price = 300,  label = "شاشة كبيرة" },
            { model = "v_res_lest_monitor",                price = 300,  label = "شاشة" },
            { model = "v_res_tre_mixer",                   price = 300,  label = "ميكسر" },
            { model = "prop_cs_cctv",                      price = 100,  label = "كاميرا مراقبة" },
            { model = "prop_ld_lap_top",                   price = 100,  label = "لابتوب" },
            { model = "prop_ld_monitor_01",                price = 100,  label = "شاشة" },
            { model = "prop_speaker_05",                   price = 500,  label = "مكبر صوت مثبت" },
            { model = "prop_tv_flat_03b",                  price = 1000, label = "شاشة مسطحة صغيرة" },
            { model = "prop_laptop_01a",                   price = 750,  label = "لابتوب مفتوح" },
            { model = "prop_tv_flat_michael",              price = 3000, label = "شاشة مسطحة معلقة" },
            { model = "prop_dyn_pc",                       price = 1000, label = "حاسوب" },
            { model = "prop_keyboard_01b",                 price = 100,  label = "لوحة مفاتيح" },
            { model = "prop_mouse_01b",                    price = 100,  label = "ماوس" },
            { model = "v_ret_gc_phone",                    price = 100,  label = "هاتف مكتبي" },
            { model = "prop_tv_flat_01",                   price = 5000, label = "شاشة مسطحة كبيرة" },
            { model = "prop_arcade_01",                    price = 5000, label = "أركيد" },
            { model = "prop_console_01",                   price = 250,  label = "وحدة ألعاب" },
            { model = "v_res_tre_dvdplayer",               price = 250,  label = "مشغل DVD" },
            { model = "prop_speaker_08",                   price = 500,  label = "مكبر صوت خشبي" },
            { model = "prop_cctv_mon_02",                  price = 300,  label = "شاشة كاميرا مراقبة" },
            { model = "prop_tv_flat_02",                   price = 2500, label = "شاشة مسطحة واقفة" },
            { model = "prop_cctv_cam_01a",                 price = 300,  label = "كاميرا مراقبة 2" },
            { model = "prop_dest_cctv_02",                 price = 300,  label = "شاشة كاميرا مراقبة 2" },
            { model = "prop_cctv_cam_07a",                 price = 300,  label = "كاميرا مراقبة 3" },
            { model = "apa_mp_h_str_avunits_04",           price = 5500, label = "أثاث شاشة مسطحة" },
            { model = "apa_mp_h_str_avunits_01",           price = 5500, label = "أثاث شاشة مسطحة 2" },
            { model = "v_club_vu_deckcase",                price = 1000, label = "مجموعة DJ" },
            { model = "v_corp_servercln",                  price = 1000, label = "خزانة خادم" },
            { model = "apa_mp_h_str_avunitl_01_b",         price = 5500, label = "أثاث شاشة مسطحة 3" },
            { model = "apa_mp_h_str_avunitl_04",           price = 5500, label = "أثاث شاشة مسطحة 4" },
            { model = "apa_mp_h_str_avunitm_01",           price = 5500, label = "أثاث شاشة مسطحة 5" },
            { model = "apa_mp_h_str_avunitm_03",           price = 5500, label = "أثاث شاشة مسطحة 6" },
            { model = "apa_mp_h_str_avunits_04",           price = 5500, label = "أثاث شاشة مسطحة 7" },
            { model = "v_res_printer",                     price = 300,  label = "طابعة" },
            { model = "apa_mp_h_acc_phone_01",             price = 100,  label = "هاتف قديم" },
            { model = "v_res_mousemat",                    price = 300,  label = "سجادة ماوس" },
            { model = "v_res_pcheadset",                   price = 300,  label = "سماعة رأس" },
            { model = "v_res_pcspeaker",                   price = 300,  label = "مكبر صوت حاسوب" },
            { model = "ba_prop_battle_club_speaker_small", price = 500,  label = "صندوق صغير" },
            { model = "ba_prop_battle_club_speaker_med",   price = 750,  label = "صندوق" },
            { model = "ba_prop_battle_club_speaker_large", price = 1000, label = "صندوق كبير" },
            { model = "v_res_pcspeaker",                   price = 300,  label = "مكبر صوت حاسوب" },
            { model = "v_res_pcwoofer",                    price = 300,  label = "صندوق صوتي حاسوب" },
            { model = "prop_controller_01",                price = 300,  label = "جهاز تحكم" },
            { model = "prop_cs_remote_01",                 price = 300,  label = "جهاز تحكم عن بعد" },
            { model = "prop_portable_hifi_01",             price = 300,  label = "راديو" },
            { model = "prop_dj_deck_02",                   price = 300,  label = "طاولة DJ" },
            { model = "prop_speaker_01",                   price = 300,  label = "مكبر صوت" }
        },
    },
    ["lighting"] = {
        label = "الإضاءة",
        items = {
            { model = "v_corp_cd_desklamp",                price = 100, label = "مصباح مكتب كورب" },
            { model = "v_res_desklamp",                    price = 100, label = "مصباح مكتب" },
            { model = "v_res_d_lampa",                     price = 100, label = "مصباح AA" },
            { model = "v_res_fa_lamp1on",                  price = 100, label = "مصباح 1" },
            { model = "v_res_fh_floorlamp",                price = 100, label = "مصباح أرضي" },
            { model = "v_res_fh_lampa_on",                 price = 100, label = "مصباح 2" },
            { model = "v_res_j_tablelamp1",                price = 100, label = "مصباح طاولة" },
            { model = "v_res_j_tablelamp2",                price = 100, label = "مصباح طاولة 2" },
            { model = "v_res_mdbedlamp",                   price = 100, label = "مصباح سرير" },
            { model = "v_res_mplanttongue",                price = 100, label = "مصباح نبات" },
            { model = "v_res_mtblelampmod",                price = 100, label = "مصباح طاولة 3" },
            { model = "v_res_m_lampstand",                 price = 100, label = "حامل مصباح" },
            { model = "v_res_m_lampstand2",                price = 100, label = "حامل مصباح 2" },
            { model = "v_res_m_lamptbl",                   price = 100, label = "مصباح طاولة 4" },
            { model = "v_res_tre_lightfan",                price = 100, label = "مروحة ضوء" },
            { model = "v_res_tre_talllamp",                price = 100, label = "مصباح طويل" },
            { model = "v_ret_fh_walllighton",              price = 100, label = "ضوء جداري" },
            { model = "v_ret_gc_lamp",                     price = 100, label = "مصباح GC" },
            { model = "prop_dummy_light",                  price = 100, label = "ضوء وامض" },
            { model = "prop_ld_cont_light_01",             price = 100, label = "ضوء جداري جانبي" },
            { model = "V_44_D_emis",                       price = 100, label = "ضوء تجريبي" },
            { model = "prop_wall_light_07a",               price = 100, label = "فانوس" },
            { model = "prop_wall_light_01a",               price = 100, label = "مصباح رخيص" },
            { model = "v_serv_tu_light2_",                 price = 100, label = "ضوء صناعي" },
            { model = "v_serv_tu_light3_",                 price = 100, label = "ضوء صناعي 2" },
            { model = "ba_prop_battle_lights_ceiling_l_a", price = 300, label = "مصباح معلق" },
            { model = "v_med_p_floorlamp",                 price = 300, label = "مصباح كبير" },
            { model = "v_club_vu_lamp",                    price = 100, label = "مصباح صغير" },
            { model = "ba_prop_battle_lights_wall_l_a",    price = 100, label = "مصباح جداري" },
            { model = "ba_prop_battle_lights_ceiling_l_c", price = 300, label = "مصباح معلق 2" },
            { model = "ba_prop_battle_lights_ceiling_l_b", price = 300, label = "ثريا 2" },
            { model = "ba_prop_battle_lights_wall_l_c",    price = 100, label = "مصباح جداري 2" },
            { model = "ba_prop_battle_lights_wall_l_b",    price = 100, label = "مصباح جداري 3" },
            { model = "hei_heist_lit_lightpendant_02",     price = 300, label = "مصباح معلق 3" },
            { model = "prop_oldlight_01b",                 price = 100, label = "مصباح جداري 4" },
            { model = "apa_mp_h_lit_floorlampnight_07",    price = 100, label = "مصباح أزرق" },
            { model = "apa_mp_h_ceiling_light_01",         price = 100, label = "تجاري" },
            { model = "apa_mp_h_ceiling_light_01_day",     price = 100, label = "تجاري 2" },
            { model = "apa_mp_h_ceiling_light_02",         price = 100, label = "ضوء سقف" },
            { model = "apa_mp_h_ceiling_light_02_day",     price = 100, label = "ضوء سقف 2" },
            { model = "ba_prop_battle_lights_ceiling_l_d", price = 100, label = "تجاري 3" },
            { model = "ba_prop_battle_lights_ceiling_l_f", price = 100, label = "ضوء سقف 3" },
            { model = "ba_prop_battle_lights_ceiling_l_e", price = 100, label = "ضوء سقف 4" },
            { model = "apa_mp_h_floorlamp_a",              price = 100, label = "مصباح أرضي" },
            { model = "apa_mp_h_floorlamp_b",              price = 100, label = "مصباح أرضي 2" },
            { model = "apa_mp_h_floorlamp_c",              price = 100, label = "مصباح أرضي 3" },
            { model = "apa_mp_h_floor_lamp_int_08",        price = 100, label = "مصباح أرضي 4" },
            { model = "apa_mp_h_lampbulb_multiple_a",      price = 100, label = "ضوء سقف 5" },
            { model = "apa_mp_h_lit_floorlamp_02",         price = 100, label = "مصباح أرضي 5" },
            { model = "apa_mp_h_lit_floorlampnight_14",    price = 100, label = "مصباح أرضي 6" },
            { model = "apa_mp_h_lit_floorlamp_03",         price = 100, label = "مصباح أرضي 7" },
            { model = "apa_mp_h_lit_floorlamp_06",         price = 100, label = "مصباح أرضي 8" },
            { model = "apa_mp_h_lit_floorlamp_10",         price = 100, label = "مصباح أرضي 9" },
            { model = "apa_mp_h_lit_floorlamp_13",         price = 100, label = "مصباح أرضي 10" },
            { model = "apa_mp_h_lit_floorlamp_17",         price = 100, label = "مصباح أرضي 11" },
            { model = "apa_mp_h_lit_lamptablenight_16",    price = 100, label = "ضوء ليلي" },
            { model = "apa_mp_h_lit_lamptablenight_24",    price = 100, label = "ضوء ليلي 2" },
            { model = "apa_mp_h_lit_lamptable_005",        price = 100, label = "ضوء ليلي 3" },
            { model = "apa_mp_h_lit_lamptable_04",         price = 100, label = "ضوء ليلي 4" },
            { model = "apa_mp_h_lit_lamptable_09",         price = 100, label = "ضوء ليلي 5" },
            { model = "apa_mp_h_lit_lamptable_14",         price = 100, label = "ضوء ليلي 6" },
            { model = "apa_mp_h_lit_lamptable_17",         price = 100, label = "ضوء ليلي 7" },
            { model = "apa_mp_h_yacht_table_lamp_01",      price = 100, label = "ضوء ليلي 8" }
        },
    },
    ["tables"] = {
        label = "طاولات",
        items = {
            { model = "v_res_d_coffeetable",            price = 500,  label = "طاولة قهوة 1" },
            { model = "v_res_d_roundtable",             price = 500,  label = "طاولة مستديرة" },
            { model = "v_res_d_smallsidetable",         price = 500,  label = "طاولة جانبية صغيرة" },
            { model = "v_res_fh_coftablea",             price = 500,  label = "طاولة أ" },
            { model = "v_res_fh_coftableb",             price = 500,  label = "طاولة ب" },
            { model = "v_res_fh_coftbldisp",            price = 500,  label = "طاولة ج" },
            { model = "v_res_fh_diningtable",           price = 500,  label = "طاولة طعام" },
            { model = "v_res_j_coffeetable",            price = 500,  label = "طاولة قهوة 2" },
            { model = "v_res_j_lowtable",               price = 500,  label = "طاولة منخفضة" },
            { model = "v_res_mdbedtable",               price = 500,  label = "طاولة سرير" },
            { model = "v_res_mddesk",                   price = 500,  label = "مكتب" },
            { model = "v_res_msidetblemod",             price = 500,  label = "طاولة جانبية" },
            { model = "v_res_m_console",                price = 500,  label = "طاولة كونسل" },
            { model = "v_res_m_dinetble_replace",       price = 500,  label = "طاولة طعام 2" },
            { model = "v_res_m_h_console",              price = 500,  label = "طاولة كونسل H" },
            { model = "v_res_m_stool",                  price = 500,  label = "كرسي؟" },
            { model = "v_res_tre_sideboard",            price = 500,  label = "طاولة جانبية" },
            { model = "v_res_tre_table2",               price = 500,  label = "طاولة 2" },
            { model = "v_res_tre_tvstand",              price = 500,  label = "طاولة تلفاز" },
            { model = "v_res_tre_tvstand_tall",         price = 500,  label = "طاولة تلفاز طويلة" },
            { model = "v_med_p_coffeetable",            price = 500,  label = "طاولة قهوة طبية" },
            { model = "v_med_p_desk",                   price = 500,  label = "مكتب طبي" },
            { model = "prop_yacht_table_01",            price = 100,  label = "طاولة يخت 1" },
            { model = "prop_yacht_table_02",            price = 100,  label = "طاولة يخت 2" },
            { model = "prop_yacht_table_03",            price = 100,  label = "طاولة يخت 3" },
            { model = "v_ret_csr_table",                price = 100,  label = "طاولة CSR" },
            { model = "v_res_mconsoletrad",             price = 250,  label = "طاولة جانبية عالية" },
            { model = "v_ilev_liconftable_sml",         price = 500,  label = "طاولة مكتب" },
            { model = "v_ret_tablesml",                 price = 350,  label = "طاولة جانبية ماريلاو" },
            { model = "apa_mp_h_yacht_coffee_table_02", price = 500,  label = "طاولة قهوة بني" },
            { model = "apa_mp_h_yacht_side_table_01",   price = 300,  label = "طاولة جانبية بني" },
            { model = "apa_mp_h_yacht_side_table_02",   price = 300,  label = "طاولة جانبية مستديرة" },
            { model = "apa_mp_h_tab_sidelrg_04",        price = 300,  label = "طاولة جانبية مستديرة 2" },
            { model = "v_club_vu_table",                price = 300,  label = "طاولة مغطاة" },
            { model = "apa_mp_h_tab_sidelrg_07",        price = 500,  label = "طاولة قهوة زجاجية" },
            { model = "bkr_prop_weed_table_01b",        price = 100,  label = "طاولة قذرة" },
            { model = "ba_prop_int_trad_table",         price = 300,  label = "طاولة قائمة" },
            { model = "apa_mp_h_str_sideboards_02",     price = 750,  label = "طاولة جانبية زجاجية" },
            { model = "apa_mp_h_yacht_coffee_table_01", price = 750,  label = "طاولة قهوة حديثة" },
            { model = "apa_mp_h_din_table_04",          price = 1000, label = "طاولة عشاء زجاجية" },
            { model = "xm_prop_base_staff_desk_01",     price = 5000, label = "مكتب + إعداد" },
            { model = "apa_mp_h_tab_coffee_07",         price = 1000, label = "طاولة جانبية مثلثة" },
            { model = "apa_mp_h_tab_coffee_08",         price = 1000, label = "طاولة جانبية بيضاء" },
            { model = "apa_mp_h_tab_sidelrg_01",        price = 1000, label = "طاولة جانبية زجاجية" },
            { model = "apa_mp_h_tab_sidelrg_02",        price = 1000, label = "طاولة جانبية زجاجية 2" },
            { model = "apa_mp_h_tab_sidesml_01",        price = 1000, label = "طاولة قابلة للطي" },
            { model = "ba_prop_int_edgy_table_01",      price = 500,  label = "طاولة رخامية" },
            { model = "ba_prop_int_edgy_table_02",      price = 500,  label = "طاولة رخامية عالية" },
            { model = "apa_mp_h_tab_sidelrg_01",        price = 1000, label = "طاولة جانبية زجاجية" },
            { model = "xm_prop_lab_desk_01",            price = 1000, label = "طاولة مختبر" }
        },
    },
    ["plants"] = {
        label = "نباتات",
        items = {
            { model = "prop_fib_plant_01",            price = 150, label = "نبات فايب" },
            { model = "v_corp_bombplant",             price = 170, label = "نبات قنبلة" },
            { model = "v_res_mflowers",               price = 170, label = "نبات زهور" },
            { model = "v_res_mvasechinese",           price = 170, label = "نبات صيني" },
            { model = "v_res_m_bananaplant",          price = 170, label = "نبات موز" },
            { model = "v_res_m_palmplant1",           price = 170, label = "نبات نخيل" },
            { model = "v_res_m_palmstairs",           price = 170, label = "نبات نخيل 2" },
            { model = "v_res_m_urn",                  price = 170, label = "نبات إبريق" },
            { model = "v_res_rubberplant",            price = 170, label = "نبات مطاط" },
            { model = "v_res_tre_plant",              price = 170, label = "نبات" },
            { model = "v_res_tre_tree",               price = 170, label = "شجرة" },
            { model = "v_med_p_planter",              price = 170, label = "وعاء زراعي" },
            { model = "v_ret_flowers",                price = 100, label = "زهور" },
            { model = "v_ret_j_flowerdisp",           price = 100, label = "زهور 1" },
            { model = "v_ret_j_flowerdisp_white",     price = 100, label = "زهور 2" },
            { model = "v_res_m_vasefresh",            price = 300, label = "فازة زهور" },
            { model = "v_res_rosevasedead",           price = 300, label = "فازة ورد 2" },
            { model = "v_res_exoticvase",             price = 300, label = "فازة زهور 2" },
            { model = "v_res_rosevase",               price = 300, label = "فازة ورد" },
            { model = "prop_pot_plant_6a",            price = 300, label = "نبات معلق" },
            { model = "prop_pot_plant_02a",           price = 300, label = "وعاء زهور" },
            { model = "apa_mp_h_acc_plant_palm_01",   price = 300, label = "نبات نخيل" },
            { model = "prop_plant_interior_05a",      price = 300, label = "صندوق زهور" },
            { model = "prop_plant_int_01a",           price = 300, label = "نبات" },
            { model = "prop_plant_int_01b",           price = 300, label = "نبات 2" },
            { model = "prop_plant_int_02a",           price = 300, label = "نبات 3" },
            { model = "prop_plant_int_02b",           price = 300, label = "نبات 4" },
            { model = "prop_plant_int_03a",           price = 300, label = "نبات 5" },
            { model = "prop_plant_int_03b",           price = 300, label = "نبات 6" },
            { model = "prop_plant_int_03c",           price = 300, label = "نبات 7" },
            { model = "prop_plant_int_04a",           price = 300, label = "نبات 8" },
            { model = "prop_plant_int_04c",           price = 300, label = "نبات 9" },
            { model = "prop_plant_int_05b",           price = 300, label = "صندوق زهور 2" },
            { model = "prop_pot_plant_01a",           price = 300, label = "وعاء نبات 2" },
            { model = "prop_pot_plant_01b",           price = 300, label = "وعاء نبات 3" },
            { model = "prop_pot_plant_01c",           price = 300, label = "وعاء نبات 4" },
            { model = "prop_pot_plant_01d",           price = 300, label = "وعاء نبات 5" },
            { model = "prop_pot_plant_01e",           price = 300, label = "وعاء نبات 6" },
            { model = "prop_pot_plant_03b",           price = 300, label = "وعاء نبات 7" },
            { model = "prop_pot_plant_05a",           price = 300, label = "وعاء نبات 8" },
            { model = "prop_pot_plant_05b",           price = 300, label = "وعاء نبات 9" },
            { model = "p_int_jewel_plant_01",         price = 300, label = "وعاء نبات 10" },
            { model = "p_int_jewel_plant_02",         price = 300, label = "وعاء نبات 11" },
            { model = "apa_mp_h_acc_vase_flowers_01", price = 300, label = "وعاء نبات 12" },
            { model = "apa_mp_h_acc_vase_flowers_02", price = 300, label = "وعاء نبات 13" },
            { model = "apa_mp_h_acc_vase_flowers_03", price = 300, label = "وعاء نبات 14" },
            { model = "apa_mp_h_acc_vase_flowers_04", price = 300, label = "وعاء نبات 15" }
        },
    },
    ["kitchen"] = {
        label = "مطبخ",
        items = {
            [1] = { model = "prop_washer_01", price = 150, label = "غسالة 1" },
            [2] = { model = "prop_washer_02", price = 150, label = "غسالة 2" },
            [3] = { model = "prop_washer_03", price = 150, label = "غسالة 3" },
            [4] = { model = "prop_washing_basket_01", price = 150, label = "سلة غسيل" },
            [5] = { model = "v_res_fridgemoda", price = 150, label = "ثلاجة 1" },
            [6] = { model = "v_res_fridgemodsml", price = 150, label = "ثلاجة 2" },
            [7] = { model = "prop_fridge_01", price = 150, label = "ثلاجة 3" },
            [8] = { model = "prop_fridge_03", price = 150, label = "ثلاجة 4" },
            [9] = { model = "prop_cooker_03", price = 150, label = "موقد" },
            [10] = { model = "prop_micro_01", price = 150, label = "ميكروويف 1" },
            [11] = { model = "prop_micro_02", price = 150, label = "ميكروويف 2" },
            [12] = { model = "prop_wok", price = 150, label = "مقلاة ووك" },
            [13] = { model = "v_res_cakedome", price = 150, label = "طبق كعكة" },
            [14] = { model = "v_res_fa_chopbrd", price = 150, label = "لوح تقطيع" },
            [15] = { model = "v_res_mutensils", price = 150, label = "أدوات المطبخ" },
            [16] = { model = "v_res_pestle", price = 150, label = "مدقة" },
            [17] = { model = "v_ret_ta_paproll", price = 150, label = "لفافة ورق 1" },
            [18] = { model = "v_ret_ta_paproll2", price = 150, label = "لفافة ورق 2" },
            [19] = { model = "v_ret_fh_pot01", price = 150, label = "وعاء 1" },
            [20] = { model = "v_ret_fh_pot02", price = 150, label = "وعاء 2" },
            [21] = { model = "v_ret_fh_pot05", price = 150, label = "وعاء 3" },
            [22] = { model = "prop_pot_03", price = 150, label = "وعاء 4" },
            [23] = { model = "prop_pot_04", price = 150, label = "وعاء 5" },
            [24] = { model = "prop_pot_05", price = 150, label = "وعاء 6" },
            [25] = { model = "prop_pot_06", price = 150, label = "وعاء 7" },
            [26] = { model = "prop_pot_rack", price = 150, label = "رف الأواني" },
            [27] = { model = "prop_kitch_juicer", price = 150, label = "عصارة" },
            [28] = { model = "v_res_ovenhobmod", price = 1000, label = "موقد" },
            [29] = { model = "v_res_mkniferack", price = 100, label = "سكين" },
            [30] = { model = "v_res_mchopboard", price = 100, label = "لوح تقطيع" },
            [31] = { model = "prop_cs_kitchen_cab_l", price = 750, label = "خزانة مطبخ واسعة" },
            [32] = { model = "prop_cs_kitchen_cab_r", price = 500, label = "خزانة مطبخ صغيرة" },
            [33] = { model = "prop_cs_kitchen_cab_r", price = 500, label = "خزانة مطبخ صغيرة" },
            [34] = { model = "v_res_tre_fridge", price = 500, label = "ثلاجة" },
            [35] = { model = "apa_mp_h_acc_coffeemachine_01", price = 500, label = "ماكينة قهوة" },
            [36] = { model = "p_new_j_counter_02", price = 500, label = "طاولة" },
            [37] = { model = "prop_bar_pump_09", price = 500, label = "مضخة 1" },
            [38] = { model = "prop_bar_pump_01", price = 500, label = "مضخة 2" },
            [39] = { model = "prop_chip_fryer", price = 500, label = "مقلي البطاطس" },
            [40] = { model = "prop_cleaver", price = 500, label = "سكين" },
            [41] = { model = "prop_coffee_mac_02", price = 500, label = "ماكينة قهوة" },
            [42] = { model = "prop_coffee_mac_01", price = 500, label = "ماكينة قهوة 2" },
            [43] = { model = "prop_cs_fork", price = 500, label = "شوكة" },
            [44] = { model = "prop_cs_sink_filler", price = 500, label = "حوض المطبخ" },
            [45] = { model = "prop_toaster_01", price = 500, label = "محمص" },
            [46] = { model = "prop_cs_plate_01", price = 500, label = "طبق" },
            [47] = { model = "prop_foodprocess_01", price = 500, label = "معالج طعام" },
            [48] = { model = "prop_food_sugarjar", price = 500, label = "وعاء سكر" },
            [49] = { model = "prop_juice_dispenser", price = 500, label = "موزع عصير" },
            [50] = { model = "prop_knife_stand", price = 500, label = "حامل سكين" },
            [51] = { model = "prop_knife", price = 500, label = "سكين 2" },
            [52] = { model = "prop_micro_04", price = 500, label = "ميكروويف 4" },
            [53] = { model = "v_ret_fh_plate3", price = 500, label = "طبق 5" },
            [54] = { model = "v_ilev_tt_plate01", price = 500, label = "طبق 6" },
            [55] = { model = "v_res_fa_grater", price = 500, label = "مبشرة" },
            [56] = { model = "v_res_tt_pizzaplate", price = 500, label = "طبق بيتزا" },
            [57] = { model = "v_ret_247_ketchup2", price = 500, label = "كاتشب" }
        },
    },
    ["bathroom"] = {
        label = "حمام",
        items = {
            [1] = { model = "prop_ld_toilet_01", price = 100, label = "مرحاض 1" },
            [2] = { model = "prop_toilet_01", price = 100, label = "مرحاض 2" },
            [3] = { model = "prop_toilet_02", price = 100, label = "مرحاض 3" },
            [4] = { model = "prop_sink_02", price = 100, label = "حوض 1" },
            [5] = { model = "prop_sink_04", price = 100, label = "حوض 2" },
            [6] = { model = "prop_sink_05", price = 100, label = "حوض 3" },
            [7] = { model = "prop_sink_06", price = 100, label = "حوض 4" },
            [8] = { model = "prop_soap_disp_01", price = 100, label = "موزع صابون" },
            [9] = { model = "prop_shower_rack_01", price = 100, label = "رف دش" },
            [10] = { model = "prop_handdry_01", price = 100, label = "مجفف يد 1" },
            [11] = { model = "prop_handdry_02", price = 100, label = "مجفف يد 2" },
            [12] = { model = "prop_towel_rail_01", price = 100, label = "سكة منشفة 1" },
            [13] = { model = "prop_towel_rail_02", price = 100, label = "سكة منشفة 2" },
            [14] = { model = "prop_towel_01", price = 100, label = "منشفة 1" },
            [15] = { model = "v_res_mbtowel", price = 100, label = "منشفة 2" },
            [16] = { model = "v_res_mbtowelfld", price = 100, label = "منشفة 3" },
            [17] = { model = "v_res_mbath", price = 100, label = "حمام" },
            [18] = { model = "v_res_mbsink", price = 100, label = "حوض" },
            [19] = { model = "v_ilev_mm_faucet", price = 100, label = "صنبور" },
            [20] = { model = "v_res_tre_washbasket", price = 250, label = "سلة غسيل" },
            [21] = { model = "prop_toilet_soap_02", price = 100, label = "صابونة" },
            [22] = { model = "prop_bar_sink_01", price = 100, label = "حوض" },
            [23] = { model = "apa_mp_h_bathtub_01", price = 1000, label = "حمام" },
            [24] = { model = "prop_toilet_brush_01", price = 1000, label = "فرشاة" },
            [25] = { model = "prop_toilet_roll_01", price = 1000, label = "لفة مرحاض" },
            [26] = { model = "prop_toilet_roll_02", price = 1000, label = "لفة مرحاض 2" },
            [27] = { model = "prop_toilet_shamp_01", price = 1000, label = "شامبو" },
            [28] = { model = "prop_toilet_shamp_02", price = 1000, label = "شامبو 2" }
        },
    },
    ["medical"] = {
        label = "طبي",
        items = {
            { model = "v_med_barrel",             price = 750, label = "برميل" },
            { model = "v_med_apecrate",           price = 750, label = "صندوق قرد" },
            { model = "v_med_apecratelrg",        price = 750, label = "صندوق قرد كبير" },
            { model = "v_med_bed1",               price = 750, label = "سرير 1" },
            { model = "v_med_bed2",               price = 750, label = "سرير 2" },
            { model = "v_med_bedtable",           price = 750, label = "طاولة سرير" },
            { model = "v_med_bench1",             price = 750, label = "مقعد 1" },
            { model = "v_med_bench2",             price = 750, label = "مقعد 2" },
            { model = "v_med_benchcentr",         price = 750, label = "مقعد وسط" },
            { model = "v_med_benchset1",          price = 750, label = "مجموعة مقاعد" },
            { model = "v_med_bigtable",           price = 750, label = "طاولة كبيرة" },
            { model = "v_med_bin",                price = 150, label = "سلة" },
            { model = "v_med_centrifuge1",        price = 750, label = "جهاز طرد مركزي" },
            { model = "v_med_cooler",             price = 750, label = "ثلاجة" },
            { model = "v_med_cor_ceilingmonitor", price = 750, label = "شاشة" },
            { model = "v_med_cor_autopsytbl",     price = 750, label = "طاولة تشريح" },
            { model = "v_med_cor_cembin",         price = 750, label = "سلة" },
            { model = "v_med_cor_cemtrolly2",     price = 750, label = "عربة" },
            { model = "v_med_cor_chemical",       price = 750, label = "مواد كيميائية" },
            { model = "v_med_cor_emblmtable",     price = 750, label = "طاولة BLM" },
            { model = "v_med_cor_fileboxa",       price = 750, label = "صندوق ملفات" },
            { model = "v_med_cor_filingcab",      price = 750, label = "خزانة ملفات" },
            { model = "v_med_cor_hose",           price = 750, label = "خرطوم" },
            { model = "v_med_cor_largecupboard",  price = 750, label = "خزانة كبيرة" },
            { model = "v_med_cor_lightbox",       price = 750, label = "صندوق إضاءة" },
            { model = "v_med_cor_medstool",       price = 750, label = "كرسي طبي" },
            { model = "v_med_cor_minifridge",     price = 750, label = "ثلاجة صغيرة" },
            { model = "v_med_cor_papertowels",    price = 750, label = "مناديل ورقية" },
            { model = "v_med_cor_photocopy",      price = 750, label = "ناسخة" },
            { model = "v_med_cor_tvstand",        price = 750, label = "حامل تلفاز" },
            { model = "v_med_cor_wallunita",      price = 750, label = "وحدة جدارية" },
            { model = "v_med_examlight",          price = 750, label = "ضوء فحص" },
            { model = "v_med_gastank",            price = 750, label = "خزان غاز" },
            { model = "v_med_hazmatscan",         price = 750, label = "فحص مواد خطرة" },
            { model = "v_med_hospheadwall1",      price = 750, label = "جدار رأس المستشفى" },
            { model = "v_med_hospseating1",       price = 750, label = "مقاعد" },
            { model = "v_med_hosptable",          price = 750, label = "طاولة مستشفى" },
            { model = "v_med_latexgloveboxblue",  price = 50,  label = "صندوق قفازات" },
            { model = "v_med_medwastebin",        price = 750, label = "سلة نفايات طبية" },
            { model = "v_med_oscillator3",        price = 750, label = "مذبذب" },
            { model = "prop_ld_health_pack",      price = 100, label = "حزمة صحة" },
        },
    },
    ["walldecoration"] = {
        label = "ديكور الجدران",
        items = {
            { model = "apa_p_h_acc_artwalll_02",      price = 1000, label = "لوحة بها علامات" },
            { model = "v_ind_cs_toolboard",           price = 500,  label = "أدوات" },
            { model = "apa_mp_stilts_bed_art",        price = 300,  label = "فن ثلاثي الأبعاد" },
            { model = "ex_office_swag_paintings03",   price = 1000, label = "لوحة أرضية" },
            { model = "ex_mp_h_acc_artwallm_03",      price = 750,  label = "لوحة تجريدية" },
            { model = "ex_p_h_acc_artwallm_04",       price = 750,  label = "لوحة تجريدية 2" },
            { model = "ex_p_h_acc_artwalll_01",       price = 1250, label = "لوحة تجريدية كبيرة" },
            { model = "apa_p_h_acc_artwalll_03",      price = 750,  label = "لوحة تجريدية 3" },
            { model = "ex_mp_h_acc_artwallm_02",      price = 750,  label = "لوحة تجريدية 4" },
            { model = "ex_p_h_acc_artwallm_03",       price = 750,  label = "لوحة تجريدية 5" },
            { model = "apa_mp_stilts_a_study_pics",   price = 500,  label = "لوحات" },
            { model = "apa_mp_h_acc_artwallm_02",     price = 750,  label = "لوحة تجريدية 6" },
            { model = "apa_mp_h_acc_artwalll_02",     price = 750,  label = "لوحة تجريدية 7" },
            { model = "apa_mp_h_acc_artwallm_04",     price = 750,  label = "لوحة تجريدية 8" },
            { model = "prop_dart_bd_cab_01",          price = 250,  label = "لوحة دارت" },
            { model = "prop_dart_bd_01",              price = 250,  label = "لوحة دارت 2" },
            { model = "hei_heist_acc_artwalll_01",    price = 250,  label = "ديكور جدران 1" },
            { model = "hei_heist_acc_artgolddisc_01", price = 250,  label = "ديكور جدران 2" },
            { model = "hei_heist_acc_artgolddisc_02", price = 250,  label = "ديكور جدران 3" },
            { model = "hei_heist_acc_artgolddisc_03", price = 250,  label = "ديكور جدران 4" },
            { model = "hei_heist_acc_artgolddisc_04", price = 250,  label = "ديكور جدران 5" },
            { model = "v_ilev_ra_doorsafe",           price = 250,  label = "ديكور فاخر" }
        },    
    },
}
